baseURL = 'http://localhost:1313/'
languageCode = 'ja-jp'
title = 'yuki9902::blog'
theme = 'mainroad'

[params]
  description = "Ameblo Archive 2009-2026"
  # サイドバーの設定（これが重要です！）
  [params.sidebar]
    home = "right"    # 右側にサイドバーを表示
    list = "right"
    single = "right"
    # 表示するウィジェット
    widgets = ["search", "recent", "archives", "categories", "taglist"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

 [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"  # 月別アーカイブ用の分類軸を追加